version: '3.1'

services:
  ##Db-контейнеры
  database:
    container_name: database
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    env_file: "./backend-api/.env"


  ##Backend-контейнеры
  backend-nginx:
    container_name: backend-nginx
    build:
      context: docker/backend
      dockerfile: nginx.docker
    volumes:
      - ./backend-api/:/var/www/application/backend-api
      - ./docker/backend/nginx/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "8091:80"
    depends_on:
      - backend-php-fpm

  backend-php-fpm:
    container_name: backend-php-fpm
    build:
      context: docker/backend
      dockerfile: php-fpm.docker
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1"
      # for macOS IP 10.254.254.254
      DOCKER_HOST: "tcp://localhost:4243"
      PHP_IDE_CONFIG: "serverName=docker"
    volumes:
      - ./backend-api/:/var/www/application/backend-api
    depends_on:
      - database
    working_dir: /var/www/application/backend-api

  ##Frontend-контейнеры
  frontend-nginx:
    container_name: frontend-nginx
    build:
      context: ./docker/frontend
      dockerfile: nginx.docker
    volumes:
      - ./frontend:/var/www/application/frontend
      - ./docker/frontend/ngnix/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-php-fpm
    ports:
      - "8090:80"

  frontend-nodejs:
    container_name: frontend-node
    image: node:8.11.3-jessie
    volumes:
      - "./frontend:/var/www/application/frontend"
    working_dir: /var/www/application/frontend
    tty: true

  ## Вспомогательные сервисы
  phpmyadmin:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    env_file: "./backend-api/.env"
    ports:
      - "8092:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root